# Darwin-specific home-manager config (macOS paths, GUI tweaks, etc.).
# copyApps.enable = false avoids "App Management" permission (25.11+ uses copyApps by default and triggers the prompt).
{ config, pkgs, lib, ... }:

{
  imports = [ ./claude-code.nix ];

  config = lib.mkIf pkgs.stdenv.isDarwin {
    programs.alacritty = {
      enable = true;
      settings = {
        window = {
          opacity = 0.88;
          padding = {
            x = 8;
            y = 8;
          };
          decorations = "Buttonless";
          option_as_alt = "Both";
        };

        font = {
          normal = {
            family = "JetBrainsMono Nerd Font Mono";
            style = "Regular";
          };
          bold = {
            family = "JetBrainsMono Nerd Font Mono";
            style = "Bold";
          };
          italic = {
            family = "JetBrainsMono Nerd Font Mono";
            style = "Italic";
          };
          size = 14.0;
        };

        scrolling.history = 50000;

        # Import Russian ЙЦУКЕН keybindings; file is generated by a derivation
        # that uses Python's chr(92) trick to produce  (TOML escape for ESC)
        # without ever embedding a raw ESC byte in any nix source string.
        general.import = [ "~/.config/alacritty/ru-bindings.toml" ];
      };
    };

    # Generate the TOML at build time via Python.
    # chr(92)+'u001b' = backslash+'u001b' = the 6-char  TOML escape.
    # The generated file has "[103;5u" etc. (valid TOML), never a raw ESC byte.
    xdg.configFile."alacritty/ru-bindings.toml".source =
      pkgs.runCommandNoCC "alacritty-ru-bindings" { } ''
        ${pkgs.python3}/bin/python3 - > "$out" << 'PYEOF'
        import sys
        bsl = chr(92)
        esc = bsl + "u001b"
        rows = [
            ("п", 103), ("й", 113), ("з", 112), ("т", 110),
            ("ы", 115), ("щ", 111), ("е", 116), ("р", 104),
            ("и",  98), ("с",  99), ("а", 102),
        ]
        lines = ["[keyboard]", "bindings = ["]
        for key, code in rows:
            lines.append(f'  {{ key = "{key}", mods = "Control", chars = "{esc}[{code};5u" }},')
        lines.append("]")
        sys.stdout.write("\n".join(lines) + "\n")
        PYEOF
      '';

    # targets.darwin.copyApps.enable = true;
    # Extend as needed
  };
}
