tavily-api-key: ENC[AES256_GCM,data:LjczD2VsCWueTtbeYburwguygO2esiOSKDa07CNfz+Kh6luohIyCA9eDc65gPoohDAl8Gc+batBjnQ==,iv:C1oGyjYndYlBmVkqgXyE6sZS60MfmLxH2O6EWh559hM=,tag:kMGh3XtvrRveOmI6ZpPtFg==,type:str]
gpg-signing-key: ENC[AES256_GCM,data:LGqK/MFyiMvgfbDHdG9w62dW8b3MKq2gFRByrlC+93qHGaIVWKKxBDgt5z7BtDHmtuEE8RJ6934RP0Qx9znUtGbdrq2De4JtFnxZ3FnxhHCOp/sIc6BDwfhwILPQhwqFHqI/G9kphcldU1LnLpSkcKR0AIrKJq8u2YgtxPAoF6FQjGvUPJYakCCAnJHoUtpRl92yE4esVsx58D2anp/DQAfHJgeupIJ6uH4zHFTvE6EBfsxGxQkeQEbpHmM7s8CUb/v56fBf4wipsS8RgAJO6eYYI2vnILvnm/WN97lOYX7BbddR09BndQcActF2zmZERkL3qv8Z8kUddLppPQDrJpwLe3RpcOAL56bdCTMCQtz3fg30aDeeoJcIlOJcfievHYDCpxsVbeqcJK6F+02xQmVtWvIidia5kayiUruz7MCwrXM/TyhPf+BzkSF4fcp5K8+dNwM89BLV00p/X88SDSqM0DqG6KRAQJ5V6BxhR2FJJFFwBftwnT2Wk85ePHCNNlYz596PtlA5vsQIdU21aFYgrIQiMyMpxUkcUzWjSMsQfBoPtphmA+zvMQ3VyeLbD+upgIuMjiwPnSufNNR0,iv:C3OqHzHxyQhYSOPvHDULHP5PWS9smdQgZuA6gcpiilc=,tag:qF8zOW3CyyPmBq5uXK8XWA==,type:str]
openrouter-api-key: ENC[AES256_GCM,data:szn9C7qWs0b7jGv6baCL6aZatvEHaV6H2Oeua4eJ03anAYp7IeB8dTSEXNEbY8anNbI3pv+iUAxHemmlYbSnMp0nf/MSoldcfQ==,iv:qCYTSQTqlKm4KyCDa/m/5VUPX/837N/8o1MpJuOv2ZM=,tag:W5WwJSZJRwbyoFVA11sYFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRm90bWExQUxtTnJUYXN6
            Y3NFajhzOGdtL1U3ZncrdHk1eVdDamxtakV3Cml6bjRNTks5ZnZkeTV3KzFnVE1W
            VFhZOHl2WUZOZHFrR2RUSk85a1V5bVEKLS0tIGUrdTA2U3hvTTFuOXFZMjY1dTVI
            TGFRSHUzMXBqSE9LdnJDQkZrWDMxSU0KZGmVS1KduLBv4YOW5JxItBf8XZLol6jP
            LN9Mv+k/NPgRFnn5S5uhKqCuFdm5eKew9KhJRD0Z0zFt502H6Gt//Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age169xghlhgpgzn0xsnae4d4nj8g3w7rnd28e5wejjr02vhjmwnjucqz8sd65
    lastmodified: "2026-09-04T22:22:38Z"
    mac: ENC[AES256_GCM,data:dK35zEJGJTh08S44TbtyuL/b1W0KlpCNFVmHOR+3crZOCdUyzmio341SGENjRhmQFclyNs3QytFybNso7m99GO2N6dZBEoaMz+rc1LTbWuFkWaFBqy7qcqALxnp6Bw83g8BlAwOafb9svu9mKxrQx/B+lOedCNV9gQGQCu35C+s=,iv:ylgms0zF6ceW4N11JqrAOHhYgxMAOl0ZV7WoSI31VFQ=,tag:XUUNpcWUyybTu0MpRhvqoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
