tavily-api-key: ENC[AES256_GCM,data:LjczD2VsCWueTtbeYburwguygO2esiOSKDa07CNfz+Kh6luohIyCA9eDc65gPoohDAl8Gc+batBjnQ==,iv:C1oGyjYndYlBmVkqgXyE6sZS60MfmLxH2O6EWh559hM=,tag:kMGh3XtvrRveOmI6ZpPtFg==,type:str]
gpg-signing-key: ENC[AES256_GCM,data:LGqK/MFyiMvgfbDHdG9w62dW8b3MKq2gFRByrlC+93qHGaIVWKKxBDgt5z7BtDHmtuEE8RJ6934RP0Qx9znUtGbdrq2De4JtFnxZ3FnxhHCOp/sIc6BDwfhwILPQhwqFHqI/G9kphcldU1LnLpSkcKR0AIrKJq8u2YgtxPAoF6FQjGvUPJYakCCAnJHoUtpRl92yE4esVsx58D2anp/DQAfHJgeupIJ6uH4zHFTvE6EBfsxGxQkeQEbpHmM7s8CUb/v56fBf4wipsS8RgAJO6eYYI2vnILvnm/WN97lOYX7BbddR09BndQcActF2zmZERkL3qv8Z8kUddLppPQDrJpwLe3RpcOAL56bdCTMCQtz3fg30aDeeoJcIlOJcfievHYDCpxsVbeqcJK6F+02xQmVtWvIidia5kayiUruz7MCwrXM/TyhPf+BzkSF4fcp5K8+dNwM89BLV00p/X88SDSqM0DqG6KRAQJ5V6BxhR2FJJFFwBftwnT2Wk85ePHCNNlYz596PtlA5vsQIdU21aFYgrIQiMyMpxUkcUzWjSMsQfBoPtphmA+zvMQ3VyeLbD+upgIuMjiwPnSufNNR0,iv:C3OqHzHxyQhYSOPvHDULHP5PWS9smdQgZuA6gcpiilc=,tag:qF8zOW3CyyPmBq5uXK8XWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRm90bWExQUxtTnJUYXN6
            Y3NFajhzOGdtL1U3ZncrdHk1eVdDamxtakV3Cml6bjRNTks5ZnZkeTV3KzFnVE1W
            VFhZOHl2WUZOZHFrR2RUSk85a1V5bVEKLS0tIGUrdTA2U3hvTTFuOXFZMjY1dTVI
            TGFRSHUzMXBqSE9LdnJDQkZrWDMxSU0KZGmVS1KduLBv4YOW5JxItBf8XZLol6jP
            LN9Mv+k/NPgRFnn5S5uhKqCuFdm5eKew9KhJRD0Z0zFt502H6Gt//Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age169xghlhgpgzn0xsnae4d4nj8g3w7rnd28e5wejjr02vhjmwnjucqz8sd65
    lastmodified: "2026-07-11T19:34:27Z"
    mac: ENC[AES256_GCM,data:Xq4A2MYfSsr8Xg+sIAvnqcUEmF9mVuSkeckXOOj4t3Z+VuA3ML3MPK/apUVQx3pG3/HBGHE274GweDHO8p9ussFE30GGmRXVNAGht257X+hTKlnMimxJpxAZEM2GGA3WfOjhjgTPYecI6cavTpOHNJUneAz0ytAhtPFowqcPz4M=,iv:o/XEYzJ9MCD8KiVNHyg7vUqeJd7/oOSA4spbYv/i/Wo=,tag:kOUy+/J9UbLTqgNO88+d5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
