tavily-api-key: ENC[AES256_GCM,data:LjczD2VsCWueTtbeYburwguygO2esiOSKDa07CNfz+Kh6luohIyCA9eDc65gPoohDAl8Gc+batBjnQ==,iv:C1oGyjYndYlBmVkqgXyE6sZS60MfmLxH2O6EWh559hM=,tag:kMGh3XtvrRveOmI6ZpPtFg==,type:str]
sops:
    age:
        - recipient: age169xghlhgpgzn0xsnae4d4nj8g3w7rnd28e5wejjr02vhjmwnjucqz8sd65
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRm90bWExQUxtTnJUYXN6
            Y3NFajhzOGdtL1U3ZncrdHk1eVdDamxtakV3Cml6bjRNTks5ZnZkeTV3KzFnVE1W
            VFhZOHl2WUZOZHFrR2RUSk85a1V5bVEKLS0tIGUrdTA2U3hvTTFuOXFZMjY1dTVI
            TGFRSHUzMXBqSE9LdnJDQkZrWDMxSU0KZGmVS1KduLBv4YOW5JxItBf8XZLol6jP
            LN9Mv+k/NPgRFnn5S5uhKqCuFdm5eKew9KhJRD0Z0zFt502H6Gt//Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:21:13Z"
    mac: ENC[AES256_GCM,data:7TiL3/wzmSUVafCFn328Q5RTVYtVQKSGdhi/ZH7/o2QLBF8nn3CsBvtOg91cUS9UMFeKxZLH61pl/I3fGKcqy4PFlBnnCv92xpRJCwqtrHeQdu/KN3aNFVyaDkDpQokLLKCMNxEP6ggiF2iNd20ioAWjxsu8RZyo21mM4vK6WVg=,iv:teuPiIfkQtEKjLBEKwW0bgC2tLuSe5PYN8UeJqVrrNs=,tag:5gjMN3LMOcxyupuejrF7tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
